/* Network+ Summer Lesson Plan — source: NetworkPlus_SummerLessons.md */
window.NETPLUS_SUMMER = {
  meta: {
    title: "Network+ Summer",
    exam: "N10-009",
    weeks: 10,
    lessons: 50,
    ptLabs: 9,
  },
  weeks: [
    {
      id: "week1",
      icon: "🧱",
      title: "Networking Fundamentals & the OSI Model",
      tagline: "Laying the foundation: how networks communicate",
      objectives: [
        "Define what a computer network is and why it matters",
        "Explain the OSI 7-layer model and each layer's purpose",
        "Differentiate LAN, WAN, MAN, and PAN network types",
        "Identify common topologies (star, mesh, bus, ring, hybrid)",
        "Install and navigate Cisco Packet Tracer",
      ],
      days: [
        { day: 1, title: "What is Networking?", content: "Introduction to networks, the Internet, and why networking matters. Course expectations and Packet Tracer setup." },
        { day: 2, title: "OSI Model — Layers 1–3", content: "Physical, Data Link, and Network layers. Signal types, MAC vs IP addressing, basic frame structure." },
        { day: 3, title: "OSI Model — Layers 4–7", content: "Transport, Session, Presentation, Application layers. TCP vs UDP overview, ports introduction." },
        { day: 4, title: "Network Types & Topologies", content: "LAN, WAN, MAN, PAN. Star, mesh, bus, ring, and hybrid topologies with real-world examples." },
        { day: 5, title: "Packet Tracer Introduction", content: "Hands-on orientation: placing devices, connecting cables, simulation mode." },
      ],
      assessments: {
        quiz: "10-question quiz covering OSI layer names, functions, and matching protocols to layers.",
        project: "Draw and label a home network diagram identifying at least 3 devices and which OSI layers they operate at.",
        ptLab: "Build a simple 3-PC star topology. Connect devices, assign IPs, and verify connectivity with ping in simulation mode.",
      },
    },
    {
      id: "week2",
      icon: "🔢",
      title: "TCP/IP & IP Addressing",
      tagline: "The language of the Internet: protocols and addresses",
      objectives: [
        "Compare the TCP/IP model to the OSI model",
        "Explain IPv4 addressing (classes, binary conversion)",
        "Calculate subnet masks and understand CIDR notation",
        "Identify public vs private IP ranges",
        "Configure basic IPv4 addresses in Packet Tracer",
      ],
      days: [
        { day: 1, title: "TCP/IP Model Deep Dive", content: "TCP/IP layers vs OSI. Encapsulation/decapsulation. PDUs: bits, frames, packets, segments." },
        { day: 2, title: "Binary & IP Addressing", content: "Binary number system, decimal-to-binary conversion. IPv4 structure: 4 octets, dotted decimal." },
        { day: 3, title: "IP Address Classes & Subnets", content: "Class A/B/C/D/E ranges, private vs public IP, APIPA. Subnet mask basics and slash notation (/24, /16)." },
        { day: 4, title: "Subnetting Fundamentals", content: "Why we subnet, calculating network/broadcast/host addresses. Step-by-step subnetting practice." },
        { day: 5, title: "IP Config Lab", content: "Configuring static IPs on routers and hosts. Reviewing ipconfig/ifconfig output and default gateways." },
      ],
      assessments: {
        quiz: "Subnetting worksheet: given a network address and mask, identify network ID, broadcast, and valid host range (5 problems).",
        project: "Create a subnet plan for a fictional small office with 3 departments from a /24 block.",
        ptLab: "Configure static IPv4 addresses on a multi-PC network with a router. Test inter-VLAN communication and document IP scheme in Packet Tracer.",
      },
    },
    {
      id: "week3",
      icon: "🔌",
      title: "Network Devices & Infrastructure",
      tagline: "The hardware that makes networks tick",
      objectives: [
        "Describe functions of hubs, switches, routers, and firewalls",
        "Explain how a switch builds and uses a MAC address table",
        "Differentiate Layer 2 and Layer 3 switching",
        "Understand access points and wireless controllers",
        "Configure basic switch settings in Packet Tracer",
      ],
      days: [
        { day: 1, title: "Hubs, Bridges & Switches", content: "Evolution from hubs to switches. Collision vs broadcast domains, MAC table, half/full duplex." },
        { day: 2, title: "Routers & Layer 3", content: "Forwarding decisions, routing tables, directly connected routes. Default and static routing overview." },
        { day: 3, title: "Firewalls, IDS/IPS & Load Balancers", content: "Stateful vs stateless firewalls, perimeter security, ACL overview. IDS vs IPS differences." },
        { day: 4, title: "Wireless APs & Controllers", content: "Infrastructure vs ad-hoc, SSID, BSS/ESS. WLC concept, fat vs thin APs." },
        { day: 5, title: "Switch Configuration Lab", content: "CLI basics: hostname, banners, passwords, enable/disable ports, port security intro." },
      ],
      assessments: {
        quiz: 'Device identification quiz: 15 scenario questions matching devices to network problems (e.g., "Which device reduces collision domains?").',
        project: "Design a small business network diagram showing correct device placement (switch, router, firewall, AP, servers) with written justification.",
        ptLab: "2-switch, 1-router topology: hostnames, passwords, trunk links. Verify with show commands.",
      },
    },
    {
      id: "week4",
      icon: "🏷️",
      title: "VLANs, Trunking & Switching Concepts",
      tagline: "Segmenting traffic for security and efficiency",
      objectives: [
        "Explain the purpose and benefits of VLANs",
        "Configure VLANs and assign access ports on a Cisco switch",
        "Describe IEEE 802.1Q trunking and VLAN tagging",
        "Understand Spanning Tree Protocol (STP) and loop prevention",
        "Implement inter-VLAN routing using router-on-a-stick",
      ],
      days: [
        { day: 1, title: "VLAN Concepts", content: "Broadcast control, security, flexibility. Default, native, management, and data VLAN distinctions." },
        { day: 2, title: "VLAN Configuration", content: "Creating VLANs, access ports, show vlan brief. Naming and documenting VLANs." },
        { day: 3, title: "Trunking & 802.1Q", content: "Trunk ports, encapsulation, 802.1Q tag structure. DTP and trunk/access modes." },
        { day: 4, title: "Spanning Tree Protocol", content: "Broadcast storms and loops, root bridge election, port states. RSTP improvements." },
        { day: 5, title: "Inter-VLAN Routing Lab", content: "Router-on-a-stick: subinterfaces, 802.1Q encapsulation, end-to-end VLAN routing test." },
      ],
      assessments: {
        quiz: "20 questions: VLAN IDs, trunk vs access, STP port states, 802.1Q fields, inter-VLAN routing methods.",
        project: "VLAN scheme for a school with 4 VLANs (Students, Staff, Admin, IoT) with security justification.",
        ptLab: "Multi-switch VLAN lab: 3 VLANs, access/trunk ports, router for inter-VLAN routing. Test with ping.",
      },
    },
    {
      id: "week5",
      icon: "🛤️",
      title: "Routing Protocols & WAN Concepts",
      tagline: "Getting data from here to anywhere",
      objectives: [
        "Distinguish between static and dynamic routing",
        "Explain distance vector vs link-state routing protocols",
        "Describe RIP, OSPF, and EIGRP at a conceptual level",
        "Understand WAN technologies: leased lines, MPLS, broadband, SD-WAN",
        "Configure and verify basic static and dynamic routing in Packet Tracer",
      ],
      days: [
        { day: 1, title: "Static vs Dynamic Routing", content: "Administrative distance, static route syntax (ip route), use cases for static routing, default route (/0)." },
        { day: 2, title: "Distance Vector Protocols (RIP)", content: "How RIP works, hop count metric, RIPv1 vs RIPv2, convergence issues, split horizon, route poisoning." },
        { day: 3, title: "Link-State Protocols (OSPF)", content: "OSPF concepts: link-state database, SPF algorithm, areas (backbone/non-backbone), neighbor adjacencies, DR/BDR." },
        { day: 4, title: "WAN Technologies", content: "Types of WAN connections: dedicated leased lines, DSL, cable, fiber, MPLS, Metro Ethernet, 4G/5G, SD-WAN overview." },
        { day: 5, title: "Dynamic Routing Lab", content: "Configure OSPF across a 3-router topology in Packet Tracer. Verify routes, test failover by disabling a link." },
      ],
      assessments: {
        quiz: "Routing protocol matching quiz + 3 routing table analysis questions. Identify best path, AD values, and protocol type from output.",
        project: "Research and write a 1-page comparison of MPLS vs SD-WAN for a mid-size enterprise. Include cost, scalability, and management considerations.",
        ptLab: "3-router OSPF lab: configure OSPF on all routers, advertise networks, verify with show ip ospf neighbor and show ip route. Test end-to-end ping.",
      },
    },
    {
      id: "week6",
      icon: "⚙️",
      title: "DNS, DHCP, NAT & Network Services",
      tagline: "The services that keep networks running automatically",
      objectives: [
        "Explain how DNS resolves hostnames to IP addresses",
        "Describe the DHCP lease process (DORA)",
        "Understand how NAT/PAT translates private IPs to public IPs",
        "Identify the role of NTP, SNMP, Syslog, and TFTP",
        "Configure a DHCP server and DNS lookup in Packet Tracer",
      ],
      days: [
        { day: 1, title: "DNS – Domain Name System", content: "Hierarchical namespace, root/TLD/authoritative servers, A, AAAA, CNAME, MX, NS record types. Recursive vs iterative queries." },
        { day: 2, title: "DHCP – Dynamic Host Config", content: "DORA process (Discover, Offer, Request, Acknowledge), lease time, scope options (gateway, DNS, subnet). DHCP relay agents." },
        { day: 3, title: "NAT & PAT", content: "Why NAT exists, inside/outside local/global addresses. Static NAT, Dynamic NAT, PAT (overloading). Verifying NAT translations." },
        { day: 4, title: "Network Management Services", content: "NTP hierarchy and stratum levels, SNMP (versions 1/2c/3), Syslog severity levels, TFTP for config backups." },
        { day: 5, title: "DHCP & DNS Lab", content: "Configure a DHCP server in Packet Tracer, assign scope options, verify automatic IP assignment on clients. Add a DNS server for name resolution." },
      ],
      assessments: {
        quiz: "Service-to-port matching quiz (DNS 53, DHCP 67/68, NTP 123, SNMP 161, Syslog 514) + 5 scenario questions on NAT troubleshooting.",
        project: "⭐ Midpoint Project: Build a complete small office network design document (IP plan, VLAN plan, routing plan, service plan) for a fictional 30-user company.",
        ptLab: "Full services lab: configure DHCP, DNS, and a NAT/PAT translation on a border router. Verify that internal hosts reach an external simulated server using domain names.",
        projectHighlight: true,
      },
    },
    {
      id: "week7",
      icon: "🔒",
      title: "Network Security Fundamentals",
      tagline: "Protecting data and devices from threats",
      objectives: [
        "Identify common threats (malware, DoS, MITM, phishing)",
        "Explain defense-in-depth and the CIA triad",
        "Describe AAA: Authentication, Authorization, Accounting",
        "Configure basic ACLs to filter traffic",
        "Understand port security and switch attack mitigation",
      ],
      days: [
        { day: 1, title: "Security Threats & Attack Types", content: "Malware types, phishing, DoS/DDoS, MITM, replay, spoofing attacks." },
        { day: 2, title: "CIA & AAA", content: "Confidentiality, Integrity, Availability. MFA, certificates. RADIUS/TACACS+ for AAA." },
        { day: 3, title: "Access Control Lists", content: "Standard vs extended ACLs, top-down logic, implicit deny, in vs out." },
        { day: 4, title: "Switch Security & Port Security", content: "MAC flooding, ARP spoofing, DHCP snooping, DAI. Port security violation modes." },
        { day: 5, title: "ACL Configuration Lab", content: "Standard and extended ACLs to permit/deny hosts and services. Verify with ping and trace." },
      ],
      assessments: {
        quiz: "15-question security quiz: threats, ACL logic, AAA protocol comparison.",
        project: "Security audit: identify 5 vulnerabilities on a diagram and propose mitigations.",
        ptLab: "Apply extended ACLs to block specific ICMP and HTTP traffic between VLANs. Enable port security on access ports. Verify with show port-security and ACL testing.",
      },
    },
    {
      id: "week8",
      icon: "📡",
      title: "Wireless Networking & Cloud Concepts",
      tagline: "Cutting the cord and moving to the cloud",
      objectives: [
        "Explain 802.11 standards (a/b/g/n/ac/ax) and characteristics",
        "Describe WEP, WPA, WPA2, WPA3 wireless encryption",
        "Identify wireless threats and mitigations",
        "Understand cloud deployment models: public, private, hybrid",
        "Differentiate IaaS, PaaS, and SaaS",
      ],
      days: [
        { day: 1, title: "802.11 Wireless Standards", content: "Wi-Fi evolution, 2.4 vs 5 GHz, channels, overlap, MIMO." },
        { day: 2, title: "Wireless Security", content: "WEP vulnerabilities, WPA/WPA2 Personal vs Enterprise, WPA3. Evil twin, rogue AP, deauth." },
        { day: 3, title: "Wireless Design & Troubleshooting", content: "Site surveys, RSSI, SNR, interference. SSID, BSS/ESS, WLC roaming." },
        { day: 4, title: "Cloud Computing Concepts", content: "NIST definition, deployment models, IaaS/PaaS/SaaS. VPN and Direct Connect." },
        { day: 5, title: "Wireless Lab", content: "Add AP, configure SSID and WPA2, connect wireless clients, verify connectivity." },
      ],
      assessments: {
        quiz: "Wireless standard matching (standard → speed, frequency, year) + 5 cloud scenario questions (which service model applies to a given scenario).",
        project: "Wireless site survey plan for a 2-floor office: AP placement, SSIDs, channels, security.",
        ptLab: "Home wireless router: SSID, WPA2, DHCP pool, NAT. Connect wired and wireless devices.",
      },
    },
    {
      id: "week9",
      icon: "🔧",
      title: "Network Troubleshooting & Tools",
      tagline: "Finding and fixing problems like a pro",
      objectives: [
        "Apply structured troubleshooting (top-down, bottom-up, divide-and-conquer)",
        "Use CLI tools: ping, traceroute, nslookup, netstat, ipconfig",
        "Interpret cable test and basic analyzer output",
        "Identify common Layer 1–3 problems and solutions",
        "Document issues and resolutions professionally",
      ],
      days: [
        { day: 1, title: "Troubleshooting Methodologies", content: "CompTIA 7-step process. Top-down, bottom-up, divide-and-conquer. When to escalate." },
        { day: 2, title: "Layer 1 & 2 Troubleshooting", content: "Cable faults, wrong cable types, CRC errors. Duplex mismatch, STP issues." },
        { day: 3, title: "Layer 3+ Troubleshooting", content: "IP misconfiguration, routing, DNS failures. ARP cache, DHCP exhaustion." },
        { day: 4, title: "CLI Tools Deep Dive", content: "ping, traceroute/tracert, nslookup/dig, netstat, ipconfig /all, arp -a, route print." },
        { day: 5, title: "Capture & Analyze Lab", content: "Packet Tracer simulation as protocol analyzer. Capture ping, HTTP, DHCP exchanges." },
      ],
      assessments: {
        quiz: "10 troubleshooting scenarios: identify likely cause and first diagnostic step.",
        project: "Broken Network: fix a topology with 6 deliberate errors. Document each fault and fix.",
        ptLab: "Troubleshooting lab: given a malfunctioning 4-router OSPF network with VLAN and ACL errors, diagnose and repair all faults. Use show and debug commands.",
      },
    },
    {
      id: "week10",
      icon: "🎓",
      title: "Review, Capstone Project & Exam Prep",
      tagline: "Bringing it all together and preparing for success",
      objectives: [
        "Synthesize 10 weeks into a cohesive understanding",
        "Build, configure, and troubleshoot a complete network",
        "Identify knowledge gaps and create a study strategy",
        "Understand N10-009 exam structure and PBQs",
        "Practice realistic exam-style questions",
      ],
      days: [
        { day: 1, title: "Exam Review — Domains 1 & 2", content: "Networking Concepts (23%) and Network Implementation (19%). Flashcard review and Q&A." },
        { day: 2, title: "Exam Review — Domains 3 & 4", content: "Network Operations (17%) and Network Security (20%). Common pitfalls and Q&A." },
        { day: 3, title: "Domain 5 & Test Strategy", content: "Troubleshooting (21%). PBQ strategy, process of elimination." },
        { day: 4, title: "Capstone Presentations", content: "Present Packet Tracer capstone projects. Peer feedback and instructor evaluation." },
        { day: 5, title: "Practice Exam & Debrief", content: "Full 90-question timed practice exam. Answer debrief and personalized study plan." },
      ],
      assessments: {
        quiz: "Full 90-question timed practice exam covering all 5 CompTIA Network+ N10-009 exam domains with performance-based questions included.",
        project: "⭐ Capstone Project: Design and build a complete enterprise branch network in Packet Tracer with VLANs, OSPF routing, DHCP, DNS, NAT, ACLs, and wireless. Submit config files + written design document.",
        ptLab: "Capstone Packet Tracer network requirements (see checklist below).",
        projectHighlight: true,
        capstoneChecklist: [
          "3 VLANs with inter-VLAN routing",
          "OSPF between 2 sites",
          "NAT/PAT on border router",
          "DHCP and DNS servers",
          "Wireless AP with WPA2 security",
          "ACLs blocking unauthorized traffic",
        ],
      },
    },
  ],
  schedule: [
    { week: 1, title: "Networking Fundamentals & the OSI Model", focus: "How networks communicate" },
    { week: 2, title: "TCP/IP & IP Addressing", focus: "Protocols and addresses" },
    { week: 3, title: "Network Devices & Infrastructure", focus: "Network hardware" },
    { week: 4, title: "VLANs, Trunking & Switching", focus: "Traffic segmentation" },
    { week: 5, title: "Routing Protocols & WAN Concepts", focus: "Routing and WANs" },
    { week: 6, title: "DNS, DHCP, NAT & Services", focus: "Automated network services" },
    { week: 7, title: "Network Security Fundamentals", focus: "Threats and controls" },
    { week: 8, title: "Wireless & Cloud Concepts", focus: "Wi-Fi and cloud models" },
    { week: 9, title: "Troubleshooting & Tools", focus: "Structured problem solving" },
    { week: 10, title: "Review, Capstone & Exam Prep", focus: "Integration and certification prep" },
  ],
  examDomains: [
    { domain: "1.0 Networking Concepts", weight: "23%", weeks: "Weeks 1, 2, 8" },
    { domain: "2.0 Network Implementation", weight: "19%", weeks: "Weeks 3, 4, 5" },
    { domain: "3.0 Network Operations", weight: "17%", weeks: "Weeks 6, 8" },
    { domain: "4.0 Network Security", weight: "20%", weeks: "Weeks 7, 8" },
    { domain: "5.0 Network Troubleshooting", weight: "21%", weeks: "Weeks 9, 10" },
  ],
  grading: [
    { item: "Weekly Mini Quizzes (×9)", each: "10 pts", total: "90 pts", notes: "Knowledge checks every week" },
    { item: "Weekly PT Labs (×9)", each: "20 pts", total: "180 pts", notes: "Hands-on Packet Tracer skills" },
    { item: "Midpoint Project (Week 6)", each: "—", total: "75 pts", notes: "Full network design document" },
    { item: "Capstone PT Project (Week 10)", each: "—", total: "100 pts", notes: "Complete enterprise network build" },
    { item: "Practice Exam (Week 10)", each: "—", total: "55 pts", notes: "Scored against N10-009 objectives" },
  ],
  tools: [
    "Cisco Packet Tracer (free with Cisco NetAcad account — netacad.com)",
    "CompTIA Network+ Study Guide (N10-009) — Professor Messer free video series recommended",
    "A computer capable of running Packet Tracer (Windows, Mac, or Linux)",
    "Lab worksheet packet (provided by instructor each week)",
  ],
  goals: [
    "Build foundational understanding of how networks are designed, configured, and secured",
    "Develop hands-on skills using Cisco Packet Tracer as a virtual lab environment",
    "Prepare students for further study toward the CompTIA Network+ certification",
    "Practice a structured troubleshooting methodology for real-world scenarios",
  ],
  resources: [
    { name: "Professor Messer Network+ (N10-009)", url: "https://www.professormesser.com/", note: "Free video course" },
    { name: "Cisco NetAcad", url: "https://www.netacad.com/", note: "Packet Tracer download + intro courses" },
    { name: "ExamCompass", url: "https://www.examcompass.com/", note: "Free practice quizzes organized by exam domain" },
    { name: "ITPro.TV / CBT Nuggets", url: "https://www.itpro.tv/", note: "Video-based learning (paid, free trials available)" },
    { name: "Subnet Practice", url: "https://subnettingpractice.com/", note: "Dedicated subnetting drill tool" },
  ],
  textbooks: [
    "CompTIA Network+ Study Guide (N10-009) by Mike Meyers — All-in-One approach",
    "CompTIA Network+ Certification All-in-One Exam Guide (McGraw-Hill)",
    "Network+ Guide to Networks by Jill West (Cengage) — classroom-friendly with labs",
  ],
  ptTips: [
    "Use File → Save regularly — Packet Tracer does not auto-save",
    "Simulation mode (Alt+Shift+S) lets you watch packets hop-by-hop — use it every lab",
    "The CLI uses Cisco IOS — ? for help, Tab for autocomplete, Ctrl+Z to exit a mode",
    "Save configs with copy running-config startup-config or they reset on reboot",
    "NetAcad skills assessments use Packet Tracer — practice labs are your best prep",
  ],
  nextSteps: [
    "Register for CompTIA Network+ N10-009 at comptia.org (Pearson VUE or online)",
    "Consider Cisco CCNA as a follow-on certification",
    "Explore CompTIA Security+ after Network+",
    "Join study communities: Reddit r/CompTIA, Discord Study Together, Anki flashcard decks",
  ],
  sourceMarkdown: "NetworkPlus_SummerLessons.md",
  disclaimer:
    "This lesson plan is designed for educational purposes. CompTIA Network+ is a registered trademark of CompTIA, Inc. Cisco Packet Tracer is a trademark of Cisco Systems, Inc.",
};
