"""Build voucher03-set.json from Tech+ Voucher 03 Test _ Wayground Questions.pdf (extracted answers a-d)."""
import json

# (correct_index 0-3, question, choices) — PDF order a,b,c,d; Q14 and Q23 had only 3 choices (added plausible 4th).
rows = [
    (0, "Which notational system is the given number A3F5 a valid representation of?", ["Hexadecimal", "Binary", "Unicode", "Decimal"]),
    (0, "Which unit of measurement is MOST commonly used to describe the storage capacity of a standard consumer hard drive today?", ["Gigabyte (GB)", "Kilobyte (KB)", "Petabyte (PB)", "Megabyte (MB)"]),
    (0, "Sasha types a command into a terminal, the computer executes it, and the results appear on her screen. Which functions are demonstrated?", ["Input, Processing, and Output", "Output and Processing", "Input, Output, and Storage", "Input, Processing, and Storage"]),
    (0, "What is the final step in the standard troubleshooting methodology?", ["Document findings, lessons learned, actions, and outcomes", "Test the theory to determine the cause", "Implement the solution", "Establish a plan of action"]),
    (0, 'A video editor is complaining that their workstation takes a long time to "render" or process a video file. To improve the speed at which the computer performs these internal calculations, which component\'s speed (measured in GHz) should be upgraded?', ["CPU", "RAM", "SSD", "NIC"]),
    (1, "A customer calls saying they can no longer access the company's internal website. You ask, \"Have you recently installed any new software or changed any settings?\" Which part of the troubleshooting methodology are you currently performing?", ["Identify the problem", "Establish a theory of probable cause", "Verify full system functionality", "Document findings and outcomes"]),
    (0, "Which unit of measurement is most appropriate for evaluating the backbone network of an enterprise-level data center?", ["Gigabits per second (Gbps)", "Megabits per second (Mbps)", "Bits per second (bps)", "Kilobits per second (Kbps)"]),
    (0, "A warehouse manager wants to use a device that can quickly scan barcodes into a database. Which type of device is required for this task?", ["Input device", "Output device", "Storage device", "Processing device"]),
    (0, "A photographer needs to back up high-resolution images to a physical disc to mail to a client who does not have reliable internet. The photographer uses a drive that writes data to the disc using a precise laser. Which type of storage technology is being utilized?", ["Optical storage", "Solid state drive", "Flash drive", "NAS"]),
    (0, "Ella wants to control her smart home devices through voice commands. Which device is designed for this?", ["Home assistant", "IP security camera", "Virtual reality system", "Augmented reality system"]),
    (0, 'A student is building a custom PC. They have laid out the case and are now installing the large, central printed circuit board that provides the electrical connections and "bus" lines for the CPU, RAM, and storage to communicate. Which component are they installing?', ["Motherboard", "BIOS", "Power Supply", "Cooling Fan"]),
    (0, "A small office has five computers that need to share files locally. To ensure that data packets are sent directly to the specific computer they are intended for (rather than broadcasting to everyone), the admin installs a device that uses MAC addresses to direct traffic. What is this device?", ["Switch", "Router", "Modem", "Access Point"]),
    (0, "Which identifier is unique to each network device and cannot be changed?", ["MAC address", "IP address", "Network name", "Serial number"]),
    (0, "Which technology allows content to be sent to a TV while allowing the source device to perform other tasks?", ["Casting", "Mirroring", "Extending", "Bluetooth tethering"]),
    (0, "Which cloud model combines on-premises infrastructure with cloud resources?", ["Hybrid", "On-premises", "Multi-cloud", "Public Cloud"]),
    (0, "Which WIFI standard that supports all three frequency bands (2.4 GHz, 5 GHz, and 6 GHz) ?", ["802.11ax", "802.11ac", "802.11b", "802.11"]),
    (0, "Which device modulates digital signals for transmission over phone lines?", ["Modem", "Router", "Switch", "Firewall"]),
    (0, "A technician is running a long data cable through a wall to connect a desktop to a wall jack. They notice the cable has eight small copper wires inside and requires a plastic \"clip-in\" connector to snap into the computer's network port. Which connector must they use?", ["RJ-45", "RJ-11", "HDMI", "USB-C"]),
    (0, "Which storage type is volatile?", ["RAM", "SSD", "HDD", "Flash drive"]),
    (0, "Which tool is used to attach an RJ45 connector to an Ethernet cable?", ["Crimper", "Cable tester", "Wire stripper", "Multimeter"]),
    (0, "What does DSL stand for?", ["Digital Subscriber Line", "Digital System Link", "Direct Satellite Link", "Dual Simultaneous Link"]),
    (0, "What is the primary role of an Access Point (AP)?", ["Establishing a wireless network for devices", "Routing traffic between different networks", "Providing a security barrier", "Sharing a single IP address with many devices"]),
    (0, "Which device serves as an intermediary for delivering services over a network?", ["Server", "Tablet", "Smartphone", "Repeater hub"]),
    (0, "Which technology is commonly used for contactless mobile payments?", ["NFC", "Bluetooth", "Wi-Fi", "Thunderbolt"]),
    (0, 'A graphic designer is complaining that their computer "stutters" when editing high-resolution 4K video files. Which internal component should be upgraded to specifically handle the math-heavy demands of rendering video and graphics?', ["GPU", "NIC", "CMOS Battery", "PSU"]),
    (0, "Which tool tests electrical connections in a cable to ensure they are functioning?", ["Cable tester", "Punch down tool", "Spectrum analyzer", "Wire stripper"]),
    (0, "After upgrading to a new high-end graphics card, a gamer finds that their Windows OS does not recognize the hardware and the screen resolution is stuck at a low setting. Which type of software does the gamer need to install to allow the OS and hardware to communicate?", ["Drivers", "Firmware", "File system", "Utility suite"]),
    (0, "Which tool allows an IT professional to interact with a user's computer from a remote location?", ["Desktop sharing tool", "Database management system", "Network monitoring software", "Content management system"]),
    (0, "Which software type is used for sharing and collaboratively editing files in the cloud?", ["Document sharing software", "Word processing software", "Database software", "Accounting software"]),
    (0, "What software type is designed to handle invoicing, payroll, and financial reporting?", ["Accounting software", "Presentation software", "Web browser", "Spreadsheet software"]),
    (0, "A user notices that their computer starts running very slowly when they open 20 different browser tabs at once. The Operating System is struggling to track which applications are currently using the system's available \"short-term\" memory. Which OS function is failing to keep up?", ["Memory management", "Disk management", "Access control", "Driver signing"]),
    (0, "A student is doing research and wants to ensure that their browsing history and cookies are not saved on a public library computer after they close the browser. Which feature should they use?", ["Private browsing / Incognito mode", "Profile synchronization", "Pop-up blocker", "Proxy settings"]),
    (0, "Which browser feature ensures consistent settings and bookmarks across multiple devices?", ["Profile synchronization", "Password management", "Default search engine", "Private browsing"]),
    (0, "A teacher needs to calculate the average grade for 100 students and create a bar chart of the results. The data is currently organized in a grid of letters and numbers. Which software application is BEST suited for this math-heavy task?", ["Spreadsheet software", "Word processing software", "Conferencing software", "Visual diagramming software"]),
    (0, "Which application would be appropriate for Generative AI?", ["Producing automated financial reports from data", "Error detection in software code", "Automating data entry", "Improving physical robot movement"]),
    (0, "What should an IT manager check to ensure a web connection is secured via SSL/TLS?", ["Valid certificates", "Enabled add-ons", "Browser cache", "Client-side scripting"]),
    (0, "Ted keeps seeing an old version of a website despite refreshing. What should he clear?", ["Browser cache", "Pop-up blocker", "Extensions", "History"]),
    (0, "Which software type allows you to express ideas graphically using shapes and connectors?", ["Visual diagramming software", "Instant messaging", "Email client", "Business-specific apps"]),
    (0, "Which OS component manages the reading and writing of data to a hard drive?", ["Disk management", "Process scheduling", "Firmware", "Memory management"]),
    (0, "What is the primary purpose of collaboration software?", ["To enable real-time teamwork through messaging and file sharing", "To manage hardware components and disk writing", "To clear browser cache and history", "To verify digital certificates for SSL/TLS"]),
    (0, "Which logic structure executes code as long as a condition is true?", ["While Loop", "If-Else Statement", "Constant", "Function"]),
    (0, "What is the purpose of an API (Application Programming Interface)?", ["To allow two different applications to communicate", "To provide a graphical interface for users", "To manage hardware resources", "To encrypt data"]),
    (0, "Which of the following is a reusable container for code that performs a specific task?", ["Function", "Variable", "Constant", "Boolean"]),
    (0, "What data type represents a single true or false value?", ["Boolean", "Integer", "Float", "String"]),
    (0, 'In programming, what is a "variable"?', ["A storage location for data that can change during execution", "A value that remains the same throughout the program", "A specialized software driver", "A hardware component"]),
    (0, "What type of language is Python?", ["Interpreted", "Compiled", "Assembly", "Machine Code"]),
    (0, "Which concept involves breaking a complex problem into smaller, manageable parts?", ["Deconstruction / Divide and Conquer", "Looping", "Cable Labeling", "Screen Resolution"]),
    (0, 'What is a "Constant" in programming?', ["A value that does not change during program execution", "A repetitive loop structure", "A type of user interface", "A connection to a database"]),
    (0, 'Which of the following is an example of a String data type?', ["\"Hello World\"", "42", "3.14", "True"]),
    (0, "What is the purpose of comments in code?", ["To explain why a line exists for human readers", "To be executed by the CPU", "To define a new variable", "To speed up execution"]),
    (0, 'An HR manager wants to find a list of all employees who have worked at the company for more than five years. They use a specific command to "ask" the database for this specific filtered information. What is this action called?', ["Query", "Schema update", "Data entry", "Relational link"]),
    (0, "What type of data is characterized by being extremely large, fast-moving, and complex?", ["Big data", "Flat data", "Small data", "Meta data"]),
    (0, "Which database type is best for simple name and ID lists without complex relationships?", ["Flat file", "Relational", "Object-oriented", "Schema-less"]),
    (0, "What stores the blueprint or structure of a database?", ["Schema", "Table", "Query", "Key"]),
    (0, "In a relational database, what uniquely identifies each record in a table?", ["Primary Key", "Foreign Key", "Schema", "Field"]),
    (0, 'Which of the following is "data about data," such as the date a file was created?', ["Metadata", "Big data", "Raw data", "Structured data"]),
    (0, "A developer is writing a script to pull customer names from a database. To ensure the script works with almost any modern relational database (like MySQL or SQL Server), they should use which standard programming language?", ["SQL", "HTML", "JavaScript", "Python"]),
    (0, 'What is the purpose of a "Foreign Key"?', ["To link two tables together", "To uniquely identify a row in its own table", "To encrypt the database", "To create a new database"]),
    (0, "Which database structure organizes data into rows and columns?", ["Relational", "Non-relational", "Key-value pair", "Document-based"]),
    (0, "An online store needs to ensure that when a customer changes their address, it updates across all orders and shipping labels automatically. Which database concept ensures this consistency?", ["Relational database", "Flat-file database", "Metadata tag", "CSV export"]),
    (0, "Why is it recommended to enforce a password expiration policy?", ["To limit the time a stolen password can be used", "To simplify account management", "To increase IT support tickets", "To ensure passwords become more complex"]),
    (0, "A user accidentally clicks a suspicious link and notices that new, unknown icons are appearing on their desktop and files are disappearing. Which security tool should be run immediately to identify and quarantine the malicious files?", ["Antivirus / Anti-malware", "Firewall", "Data encryption", "Multi-factor authentication"]),
    (0, "What is the most effective strategy for securing a small business wireless network for internal and guest users?", ["Create separate SSIDs for internal and guest users", "Use the same SSID for everyone", "Disable SSID broadcasting", "Use WEP encryption"]),
    (0, "Which of the following is a \"corrective\" control?", ["Restoring backups after a ransomware attack", "Putting up a \"No Trespassing\" sign", "Installing a motion sensor", "Writing a security policy"]),
    (0, 'What does the "A" in the CIA triad stand for?', ["Availability", "Authentication", "Authorization", "Accounting"]),
    (0, "Which of the following involves manipulating people into giving up confidential information?", ["Social Engineering", "Wiretapping", "Eavesdropping", "Snooping"]),
    (0, "What is the purpose of Multi-Factor Authentication (MFA)?", ["To require more than one form of evidence to verify identity", "To allow users to use many different passwords", "To speed up the login process", "To bypass the need for a username"]),
    (0, "Which threat involves encrypting a user's files and demanding payment for the key?", ["Ransomware", "Trojan Horse", "Spyware", "Adware"]),
    (0, 'A small business owner receives an email that looks like it is from their bank, asking them to click a link and "verify" their login credentials immediately. What is this an example of?', ["Phishing", "Ransomware", "Wiretapping", "Tailgating"]),
    (0, "Which of the following is a physical security control?", ["A badge reader on a door", "An antivirus software program", "A firewall configuration", "A complex password policy"]),
    (0, "Which of the following is an example of a physical security control?", ["A physical lock", "A complex password", "A file encryption system", "A digital certificate"]),
    (0, 'What is "Principle of Least Privilege"?', ["Giving users only the access they need to do their job", "Giving all users administrative rights", "Allowing users to choose their own access levels", "Revoking all access after 5:00 PM"]),
    (0, "Which protocol is used to secure web traffic with SSL/TLS?", ["HTTPS", "HTTP", "FTP", "SMTP"]),
    (0, 'A company wants to prevent unauthorized hackers from the internet from "knocking" on their private internal network ports. They install a security barrier at the edge of the network that inspects every incoming packet of data against a set of security rules. What is this barrier?', ["Firewall", "VPN", "Switch", "Load Balancer"]),
    (0, "The first programs to load into a computer", ["BIOS", "Operating System", "Microsoft Office", "Printer Drivers"]),
]

assert len(rows) == 75

out = {
    "id": "tech-voucher-test-03",
    "title": "Tech+ Voucher Test 03",
    "source": "Tech+ Voucher 03 Test _ Wayground Questions.pdf",
    "questions": [{"q": q, "choices": ch, "correct": c} for c, q, ch in rows],
}

path = __file__.replace("gen-voucher03-set.py", "voucher03-set.json")
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, indent=2, ensure_ascii=False)
print("wrote", path, "n=", len(out["questions"]))
